Some additional methods for streams
asuiu/streamerate pull request #13
Opened 2024-10-24 12:59 UTC by jftsang

I have found these useful for working with key-value pairs, dictionaries and Pandas dataframes.

2024-10-29 16:41 UTC, asuiu requested changes
Looks good overall to me, I suggest just a few minor changes.

2024-10-29 16:41 UTC, asuiu commented on streamerate/streams.py
> +    def makeMapping(
`makeMapping`: consider using `pairWith` to highlight that each element is paired with the result of applying `f`

2024-10-29 16:41 UTC, asuiu commented on streamerate/streams.py
> +    def makeInverseMapping(
`makeInverseMapping`: consider using `pairBy`, which is concise and mirrors `pairWith`, indicating that the function is applied to produce the first element (key) in each tuple.

2024-10-29 16:41 UTC, asuiu commented on streamerate/tests/test_Streams.py
> +            "Not implemented, to avoid making Pandas a dependency of "
This is okay to implement, as the Pandas will be a dependency just of the tests, not of the library, so feel free to include the pandas as dependency to the `pyproject.toml` -> `[tool.poetry.dev-dependencies]`

2024-10-30 11:33 UTC, jftsang commented
Thanks for the feedback!

2024-10-30 21:07 UTC, asuiu approved these changes
LGTM, Ship it!
```
              |    |    |                 
             )_)  )_)  )_)              
            )___))___))___)\            
           )____)____)_____)\\
         _____|____|____|____\\\__
---------\                   /---------
  ^^^^^ ^^^^^^^^^^^^^^^^^^^^^
    ^^^^      ^^^^     ^^^    ^^
         ^^^^      ^^^
```

2024-10-30 21:11 UTC, merged

2024-10-30 21:24 UTC, asuiu commented
@jftsang 
I've compiled a new version and uploaded it to PyPi: https://pypi.org/project/streamerate/1.1.2/

Many thanks for your contribution!