implemented new method for_each on _IStream
asuiu/streamerate pull request #5
Opened 2023-06-18 00:04 UTC by roymanigley

Closes #1

2023-06-20 10:25 UTC, asuiu commented
Hi @roymanigley ,

Thank you for your contribution!

Please take into account that the same functionality of the `for_each` method can be achieved by using `map(f).size()`, thus do you really need the `for_each` as a separate method?

2023-06-20 20:07 UTC, roymanigley commented
Hi @asuiu 
Thanks for your feedback, and your nice library. To me it would be convenient to be able to pass a lambda which does not have to return any thing and without calling an addition method on the stream.
I know that the method is not realy needed and there is a workaround, but to me this would be a nice feature, since it would make the code more readable.

2023-07-10 22:22 UTC, asuiu commented
@roymanigley 
There are some minor errors in this PR implementation, but to avoid the PR ping-pong, I have just implemented the `for_each` function which should work for all situations, and have also added it in the new version of the library on PyPi: https://pypi.org/project/streamerate/1.0.1/

Please feel free to comment and contribute with new ideas.

Thanks for your contribution @roymanigley!

2023-07-10 22:30 UTC, asuiu requested changes

2023-07-11 18:32 UTC, closed without merging